name: Run Pytest 3.7 General

on:
  push:
    branches:
      - main
    paths:
      - 'tests/test_import_utils.py'
      - 'tests/test_model_to_dict.py'
      - 'tests/test_utils.py'
      - 'tests/base/test_base.py'
  pull_request:
    branches:
      - main
    paths:
      - 'tests/test_import_utils.py'
      - 'tests/test_model_to_dict.py'
      - 'tests/test_utils.py'
      - 'tests/base/test_base.py'

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
      - name: Pytest 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install base dependencies
        run: |
          sudo apt-get install libsndfile1
          python -m pip install --upgrade pip
          pip install -e .
      - name: Install dependencies for tests
        run: |
          pip install -r requirements.txt
          pip install -e ".[test]"
          pip install -e .[encoders-audio-tfhub]
      - name: Test Vectorai models
        env:
            VI_USERNAME: ${{ secrets.VI_USERNAME }}
            VI_API_KEY: ${{ secrets.VI_API_KEY }}
        run: |
          pytest tests/test_import_utils.py
          pytest tests/test_model_to_dict.py
          pytest tests/test_utils.py
          pytest tests/base/test_base.py
