name: Run Pytest 3.6 Image Text

on:
  push:
    branches:
      - main
    paths:
      - 'vectorhub/bi_encoders/text_image/**'
      - 'tests/bi_encoders/text_image/**'
  pull_request:
    branches:
      - main
    paths:
      - 'vectorhub/bi_encoders/text_image/**'
      - 'tests/bi_encoders/text_image/**'

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pytest 3.6
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install base dependencies
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          sudo apt-get install libsndfile1
          python -m pip install --upgrade pip
          pip install -e .

      - name: Install dependencies for tests
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          pip install -r requirements.txt
          pip install -e ".[test]"

      - name: Install and test for image-text-torch
        env:
            VH_USERNAME: ${{ secrets.VH_USERNAME }}
            VH_API_KEY: ${{ secrets.VH_API_KEY }}
        run: |
          pip install -e ".[clip]"
          pytest tests/bi_encoders/text_image/torch
