name: Update Badges

on:
  schedule:
    - cron: "10 * * * *"

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pytest 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Download badges
      run: |
        python -m pip install -r requests
        python scripts/download_badges.py
